name: Update NBER Papers Weekly

on:
  # 允许手动触发，方便测试
  workflow_dispatch:
  # 定时触发：每周一早上 5:00 (UTC)，大约是北京时间中午13点
  schedule:
    - cron: '0 5 * * 1'

# --- 添加这部分代码 --- #
permissions:
  contents: write
# -------------------- #

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出你的仓库代码
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. 运行更新脚本
      - name: Run update script
        env:
          KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
        run: python update_nber.py

      # 5. 提交并推送 README.md 的更改
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update weekly NBER papers"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: README.md
